### Python Data Structure

### List (mutable)

In [2]:
lst = [1,2,3,4,5,6]

In [4]:
type(lst)

list

In [7]:
lst[0:5:2] # [start:stop:step]

[1, 3, 5]

In [8]:
lst.append(7)

In [9]:
lst

[1, 2, 3, 4, 5, 6, 7]

In [10]:
lst.append(['A','B','C'])

In [11]:
lst

[1, 2, 3, 4, 5, 6, 7, ['A', 'B', 'C']]

In [12]:
lst2 = [1,2,3,4,5,6]

In [19]:
lst_times2=[]

for x in lst2:
    print('====', x)
    print('times 2:', x*2)
    lst_times2.append(x*2)
    print(lst_times2)

==== 1
times 2: 2
[2]
==== 2
times 2: 4
[2, 4]
==== 3
times 2: 6
[2, 4, 6]
==== 4
times 2: 8
[2, 4, 6, 8]
==== 5
times 2: 10
[2, 4, 6, 8, 10]
==== 6
times 2: 12
[2, 4, 6, 8, 10, 12]


In [20]:
lst_times2

[2, 4, 6, 8, 10, 12]

In [21]:
#append() : add all the elements pass to it as a single element
#extend(): add the elements one by one into the list

lst_times2.extend([14,16,18])
lst_times2

[2, 4, 6, 8, 10, 12, 14, 16, 18]

##### remove value from list

In [22]:
del lst_times2[5] # remove index 5 element from the list
a.pop(1) # remove index 1 element from the list

In [23]:
lst_times2

[2, 4, 6, 8, 10, 14, 16, 18]

#### Sort the list

In [25]:
lst3= [2,4,1,3]

In [27]:
lst3.sort()

In [36]:
lst3

[1, 2, 3, 4]

In [37]:
# list is mutable
lst3[0]=1111

In [38]:
lst3

[1111, 2, 3, 4]

In [34]:
# primetive type: int, float, string,boolean
print(type(True))
print(type(3))
print(type(3.5566)) 
print(type('word'))

<class 'bool'>
<class 'int'>
<class 'float'>
<class 'str'>


### Tuple (immutable, unchangeble)

In [39]:
tple = (1,2,3,4)

In [40]:
type(tple)

tuple

In [41]:
tple[:3]

(1, 2, 3)

In [42]:
tple.append(199999)

AttributeError: 'tuple' object has no attribute 'append'

### Set (mutable, not able to index)

In [44]:
lst=[1,2,2,2,7,6,5]
set1= set(lst) # unique , 
set1

{1, 2, 5, 6, 7}

In [45]:
set1.add(1000)
set1

{1, 2, 5, 6, 7, 1000}

In [46]:
type(set1)

set

In [47]:
set1[:1]

TypeError: 'set' object is not subscriptable

In [48]:
list(set1)[:1]

[1]

### Dictionary (mutable)

In [49]:
# key:value
my_dict = {
    'Amy':90,
    'John':80,
    'Alex':70
}

print(type(my_dict))

<class 'dict'>


In [50]:
my_dict

{'Amy': 90, 'John': 80, 'Alex': 70}

In [51]:
my_dict['Amy']= 100

In [52]:
my_dict

{'Amy': 100, 'John': 80, 'Alex': 70}

In [53]:
my_dict.values()

dict_values([100, 80, 70])

## Numpy

In [54]:
import numpy as np

In [56]:
np_array = np.array([1,2,3,4])

In [58]:
type(np_array)

numpy.ndarray

In [61]:
np_array2 = np.array([
    [1,2,3,4],[1,2,3,4]
])

In [65]:
np_array2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [64]:
np_array2.shape # check numpy array dimensions ( 2 * 4)

(2, 4)

In [75]:
length= 10000000
a = np.random.rand(length)
b = np.random.rand(length)

In [76]:
import time
start_time=time.time()

c=0
for i in range(length):
    c+= a[i]*b[i]

print('fininsh time:', (time.time()-start_time))

fininsh time: 4.662510871887207


In [71]:
c

24.513474820102363

In [77]:
start_time=time.time()
np.dot(a,b)
print('fininsh time:', (time.time()-start_time))

fininsh time: 0.007929801940917969


## Pandas

In [78]:
import pandas as pd

In [79]:
file = 'Times Higher Education.csv' # remeber to add the path of the file

In [87]:
df= pd.read_csv(file,usecols=['location','overall'],nrows=3)

In [99]:
df

location  overall
0  Massachusetts     91.9
1       New York     90.6
2  Massachusetts     90.4

In [100]:
df.T

0         1              2
location  Massachusetts  New York  Massachusetts
overall            91.9      90.6           90.4

In [101]:
df['location']

0    Massachusetts
1         New York
2    Massachusetts
Name: location, dtype: object

In [89]:
df.shape

(3, 2)

In [92]:
type(df)

pandas.core.frame.DataFrame

In [91]:
df.loc[df['location']=='New York']

location  overall
1  New York     90.6

In [95]:
example = np.array([0,1,2,3,4,5,6,7,8,9])

In [97]:
example[example%2 == 1]

array([1, 3, 5, 7, 9])

In [98]:
example%2 == 1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

### Interview Question

In [ ]:
# num = np.array([[1,2,3],[4,5,6],[7,8,9]]) Extract the value 8 using 2D indexing

Num[2,1]